[package]
name = "cubecl-test"
version = "0.1.0"
edition = "2021"

[features]
default = ["wgpu"]
wgpu = []

[dependencies]
cubecl = { version = "0.5.0", features = ["wgpu"] }
nalgebra = "0.33.2"
bytemuck = "1.23.0"
serde = { version = "1.0", features = ["derive"] }
